entryPoints:
  traefik:
    address: :8080
  tcp-1:
    address: :4043
  tcp-2:
    address: :4044
  tcp-3:
    address: :4045
  web:
    address: :8000
  web-tls:
    address: :8001

providers:
  docker: {}
  file:
    directory: /etc/traefik/fileprovider
    watch: true
  consul:
    endpoints:
      - 172.16.20.116:8500
    rootKey: traefik

api:
  insecure: true
