entryPoints:
  traefik:
    address: :8080
  http:
    address: :80
  https:
    address: :443
  tcp-1:
    address: :4043
  tcp-2:
    address: :4044
  tcp-3:
    address: :4045
  tcp-4:
    address: :4046
  tcp-5:
    address: :4047
  tcp-6:
    address: :4048

providers:
  docker: {}
  file:
    directory: /etc/traefik/fileprovider
    watch: true

api:
  insecure: true
