server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

# Loki url
clients:
  - url: https://467009:eyJrIjoiNzc5MzliNDE4NDMzZjNjNWRhMWVhNTA1MjFlZGM2ZTE3M2RiMTZhYSIsIm4iOiJ0ZXN0IiwiaWQiOjgzMzEzOX0=@logs-prod-012.grafana.net/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  - job_name: mgc_logs
    kafka:
      brokers:
        - kafka:9092
      topics:
        - mgc_logs
      group_id: promtail_mgc_logs
      labels:
        job: mgclogs
      use_incoming_timestamp: true
