version: "3"
services:
    influxDB:
        image: influxdb:latest
        container_name: influxDB
        restart: always
        environment:
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_USERNAME: root
            DOCKER_INFLUXDB_INIT_PASSWORD: my-root-password
            DOCKER_INFLUXDB_INIT_ORG: test_org
            DOCKER_INFLUXDB_INIT_BUCKET: test_bucket
            DOCKER_INFLUXDB_INIT_RETENTION: 1w
        ports:
            - 8086:8086

    redis-json:
        image: redislabs/rejson:latest
        container_name: redis-json
        restart: always
        ports:
            - 6379:6379

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: my-root-password
            MYSQL_DATABASE: test_db
            MYSQL_USER: ckk
            MYSQL_PASSWORD: my-root-password
        ports:
            - 3306:3306

    consul_server:
        image: consul:latest
        container_name: consul_server
        restart: always
        ports:
            - 8300:8300
            - 8301:8301
            - 18500:8500 # 客户端接口监听端口
        command:
            - agent
            - -server
            - -bind=0.0.0.0
            - -client=0.0.0.0 # 不暴露客户端接口无法访问ui
            - -bootstrap-expect=1
            - -node=consul-server-1
            - -ui

    consul_client:
        image: consul:latest
        container_name: consul_client
        restart: always
        ports:
            - 8500:8500
        command:
            - agent
            - -bind=0.0.0.0
            - -client=0.0.0.0
            - -retry-join=${CONSUL_SERVER_HOST}
            - -node=consul-client-1
        depends_on:
            - consul_server

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - 15672:15672
            - 5672:5672
        environment:
            - RABBITMQ_DEFAULT_USER=Teld
            - RABBITMQ_DEFAULT_PASS=Teld@Teld.cn
