receivers:
  otlp:
    protocols:
      grpc:
        endpoint: :4317
      http:
        endpoint: :4318

processors:
  batch:

exporters:
  otlp:
    endpoint: tempo:4317 # tempo trace
    tls:
      insecure: true
    headers:
      X-Scope-OrgID: ckk # 配合tempo多租户模式

extensions:
  health_check:
    endpoint: :13133
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679

# 通过`service`块来组合/使能上面的配置
service:
  extensions:
    - health_check
    - pprof
    # - zpages # zpages默认端口55679在Windows上容易被系统占用
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
